// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// extractXmlEntries
Rcpp::StringVector extractXmlEntries(const std::string& xmlFile, const std::string& extractDir);
RcppExport SEXP _biodbHmdb_extractXmlEntries(SEXP xmlFileSEXP, SEXP extractDirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type xmlFile(xmlFileSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type extractDir(extractDirSEXP);
    rcpp_result_gen = Rcpp::wrap(extractXmlEntries(xmlFile, extractDir));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP run_testthat_tests(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_biodbHmdb_extractXmlEntries", (DL_FUNC) &_biodbHmdb_extractXmlEntries, 2},
    {"run_testthat_tests", (DL_FUNC) &run_testthat_tests, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_biodbHmdb(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
