# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convolution.
#'
#' Example function taken from Rcpp vignette "Rcpp-introduction".
#' This function is callable from R as a normal R function, it is thus tested 
#' as a normal R function.
#'
#' @param a     A numeric vector.
#' @param b     A numeric vector.
#' @return  The result as a numeric vector.
#'
convolve_cpp <- function(a, b) {
    .Call('_biodbHmdb_convolve_cpp', PACKAGE = 'biodbHmdb', a, b)
}

extractXmlEntries <- function(xmlFile, extractDir) {
    .Call('_biodbHmdb_extractXmlEntries', PACKAGE = 'biodbHmdb', xmlFile, extractDir)
}

